name: 'GitHub Environment Action'
description: 'Configure GitHub Environment from your workflow'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
    default: ${{ github.token }}  
  environment: 
    description: 'GitHub Environment name'
    required: true
  state: 
    description: 'GitHub Environment state'
    required: true
    default: inactive
  url:
    description: 'Deployment url'
    required: false
  description:
    description: 'Deployment description'
    required: false 
  transient_environment:
    description: 'Transient environment'
    required: false
    default: false
  production_environment:
    description: 'Production environment'
    required: false
    default: false


runs:
  using: 'node12'
  main: 'index.js'
  