name: 'GitHub Environment Action'
description: 'Configure GitHub Environment from your workflow'
inputs:
  environment: 
    description: 'GitHub Environment name'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
  